Add movement penalty to armor
ggutenberg/roll20-character-sheets pull request #1
Opened 2021-08-24 18:40 UTC by bpolge

## Changes / Comments
Added movement penalty to the armor items.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

2021-08-24 18:49 UTC, ggutenberg requested changes
Nice first crack. I look forward to continued submissions :)

2021-08-24 18:49 UTC, ggutenberg commented on Palladium Rifts by Grinning Gecko/src/js/armor.js
> +const { on } = require("gulp");
This is a stupid VSCode thing that it tries to inject every time you type `on`. Delete it - it breaks shit. I'm sure there's a way to get VSCode to stop doing it, but idk how.

2021-08-24 18:49 UTC, ggutenberg commented on Palladium Rifts by Grinning Gecko/src/partials/armor.html
> +<input type="number" placeholder="Movement Penalty" name="attr_mvmt" />
```suggestion
<input type="number" placeholder="Movement Penalty" name="attr_movementpenalty" />
```
I like to be verbose, especially in here where there's so many similarly named attributes.

2021-08-24 18:49 UTC, ggutenberg commented on Palladium Rifts by Grinning Gecko/src/js/armor.js
> +  const penalty = e.target.value;
```suggestion
  const penalty = +e.target.value;
```

2021-08-24 18:49 UTC, ggutenberg commented on Palladium Rifts by Grinning Gecko/src/js/armor.js
> +  const newMvmt = a - (a * penalty);
This won't work because `a` is an object. Also `a["repeating_movement_mph"]` will be a string, even though it's `input type="number"`. So you need to numberize it.

```suggestion
  const newMvmt = +a["repeating_movement_mph"] - (+a["repeating_movement_mph"] * penalty);
```

2021-08-24 18:52 UTC, ggutenberg requested changes

2021-08-24 18:52 UTC, ggutenberg commented on Palladium Rifts by Grinning Gecko/src/js/armor.js
> +  const penalty = e.target.value;
Oops. Previous comment not right. Should be:

```suggestion
  const penalty = +e.newValue;
```

See https://wiki.roll20.net/Sheet_Worker_Scripts#change:.3Cattribute_name.3E .

2021-08-24 23:27 UTC, bpolge commented on Palladium Rifts by Grinning Gecko/src/js/movement.js
> +  const attacksAttrName = `repeating_profiles_${orderedSectionIds[0]}_attacks`;
This should probably look for the active profile at some point.

2021-08-25 00:23 UTC, ggutenberg approved these changes

2021-08-25 00:24 UTC, merged